# frontend/values.yaml
replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 400m
  requests:
    cpu: 200m




hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
