apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: custom-con
          image: 350515911022.dkr.ecr.us-east-2.amazonaws.com/database:v1
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
              readOnly: true
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
        - name: mysql-config
          configMap:
            name: mysql-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
spec:
  storageClassName: aws-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi





