---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 350515911022.dkr.ecr.us-east-2.amazonaws.com/new_chatapp:42

---
apiVersion: v1
kind: Service
metadata:
  name: app-cont
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - name: backend
      port: 8000
      targetPort: 8000