# frontend/templates/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap
data:
  nginxconf.conf: |
    server {
      listen 80 ;
      server_name _default;
      root /new_chatapp/fundoo;
      location / {
        proxy_pass http://app-cont:8000;
      }
    }

